// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raika_OCC_10_API_10_API.Entidades;

#nullable disable

namespace Raika_OCC_10_API.Migrations
{
    [DbContext(typeof(OCCRaikaDbContext))]
    [Migration("20260902183935_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.Catalogos.EstadoCivil", b =>
                {
                    b.Property<int>("EstadoCivilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoCivilId"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoCivilId");

                    b.ToTable("EstadosCiviles");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.Catalogos.Sexo", b =>
                {
                    b.Property<int>("SexoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SexoId"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SexoId");

                    b.ToTable("Sexos");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.Coordenada", b =>
                {
                    b.Property<Guid>("CoordenadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("longitud")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoordenadaId");

                    b.ToTable("Coordenadas");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.Domicilios.EntidadFederativa", b =>
                {
                    b.Property<int>("EntidadFederativaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntidadFederativaId"));

                    b.Property<string>("NombreEntidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntidadFederativaId");

                    b.ToTable("EntidadesFederativas");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.EstructuraEclesial.Capilla", b =>
                {
                    b.Property<int>("CapillaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapillaId"));

                    b.Property<string>("ClaveCapilla")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaveDecanato")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CapillaId");

                    b.HasIndex("ClaveCapilla")
                        .IsUnique();

                    b.HasIndex("ClaveDecanato");

                    b.ToTable("Capillas");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.EstructuraEclesial.Colonia", b =>
                {
                    b.Property<int>("ColoniaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColoniaId"));

                    b.Property<string>("ClaveColonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaveDecanato")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColoniaId");

                    b.HasIndex("ClaveColonia")
                        .IsUnique();

                    b.HasIndex("ClaveDecanato");

                    b.ToTable("Colonias");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.EstructuraEclesial.Decanato", b =>
                {
                    b.Property<int>("DecanatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DecanatoId"));

                    b.Property<string>("ClaveDecanato")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaveZonaPastoral")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DecanatoId");

                    b.HasIndex("ClaveDecanato")
                        .IsUnique();

                    b.HasIndex("ClaveZonaPastoral");

                    b.ToTable("Decanatos");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.EstructuraEclesial.EspacioCatolico", b =>
                {
                    b.Property<int>("EspacioCatolicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspacioCatolicoId"));

                    b.Property<string>("ClaveDecanato")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaveEspacioCatolico")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspacioCatolicoId");

                    b.HasIndex("ClaveDecanato");

                    b.HasIndex("ClaveEspacioCatolico")
                        .IsUnique();

                    b.ToTable("EspaciosCatolicos");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.EstructuraEclesial.ZonaPastoral", b =>
                {
                    b.Property<int>("ZonaPastoralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZonaPastoralId"));

                    b.Property<string>("ClaveZonaPastoral")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZonaPastoralId");

                    b.HasIndex("ClaveZonaPastoral")
                        .IsUnique();

                    b.ToTable("ZonasPastorales");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.Perfil.Laico", b =>
                {
                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DesarrolloApostolado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionApostolado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PerfilId");

                    b.ToTable("Laicos");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.Perfil.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AMaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicionVida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EstadoCivilId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SantoPatron")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SexoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoCivilId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SexoId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.Perfil.Sacerdote", b =>
                {
                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColoniaMinisterio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionMinisterio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ministerio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombramiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PerfilId");

                    b.ToTable("Sacerdotes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Raika_OCC_10_API.Entidades.Perfil.Perfil", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Raika_OCC_10_API.Entidades.Perfil.Perfil", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Raika_OCC_10_API.Entidades.Perfil.Perfil", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Raika_OCC_10_API.Entidades.Perfil.Perfil", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.EstructuraEclesial.Capilla", b =>
                {
                    b.HasOne("Raika_OCC_10_API.Entidades.EstructuraEclesial.Decanato", "Decanato")
                        .WithMany("Capillas")
                        .HasForeignKey("ClaveDecanato")
                        .HasPrincipalKey("ClaveDecanato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decanato");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.EstructuraEclesial.Colonia", b =>
                {
                    b.HasOne("Raika_OCC_10_API.Entidades.EstructuraEclesial.Decanato", "Decanato")
                        .WithMany("Colonias")
                        .HasForeignKey("ClaveDecanato")
                        .HasPrincipalKey("ClaveDecanato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decanato");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.EstructuraEclesial.Decanato", b =>
                {
                    b.HasOne("Raika_OCC_10_API.Entidades.EstructuraEclesial.ZonaPastoral", "ZonaPastoral")
                        .WithMany("Decanatos")
                        .HasForeignKey("ClaveZonaPastoral")
                        .HasPrincipalKey("ClaveZonaPastoral")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZonaPastoral");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.EstructuraEclesial.EspacioCatolico", b =>
                {
                    b.HasOne("Raika_OCC_10_API.Entidades.EstructuraEclesial.Decanato", "Decanato")
                        .WithMany("EspacioCatolicos")
                        .HasForeignKey("ClaveDecanato")
                        .HasPrincipalKey("ClaveDecanato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decanato");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.Perfil.Laico", b =>
                {
                    b.HasOne("Raika_OCC_10_API.Entidades.Perfil.Perfil", "Perfil")
                        .WithOne("Laico")
                        .HasForeignKey("Raika_OCC_10_API.Entidades.Perfil.Laico", "PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.Perfil.Perfil", b =>
                {
                    b.HasOne("Raika_OCC_10_API.Entidades.Catalogos.EstadoCivil", "EstadoCivil")
                        .WithMany()
                        .HasForeignKey("EstadoCivilId");

                    b.HasOne("Raika_OCC_10_API.Entidades.Catalogos.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId");

                    b.Navigation("EstadoCivil");

                    b.Navigation("Sexo");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.Perfil.Sacerdote", b =>
                {
                    b.HasOne("Raika_OCC_10_API.Entidades.Perfil.Perfil", "Perfil")
                        .WithOne("Sacerdote")
                        .HasForeignKey("Raika_OCC_10_API.Entidades.Perfil.Sacerdote", "PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.EstructuraEclesial.Decanato", b =>
                {
                    b.Navigation("Capillas");

                    b.Navigation("Colonias");

                    b.Navigation("EspacioCatolicos");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.EstructuraEclesial.ZonaPastoral", b =>
                {
                    b.Navigation("Decanatos");
                });

            modelBuilder.Entity("Raika_OCC_10_API.Entidades.Perfil.Perfil", b =>
                {
                    b.Navigation("Laico");

                    b.Navigation("Sacerdote");
                });
#pragma warning restore 612, 618
        }
    }
}
